/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.swett.intro2;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        ArrayPlay classUnderTest = new ArrayPlay();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
